### ISSUE TITLE
Add authorship information

### ISSUE THREAD

**Issue by avahoffman** [jhudsl/GDSCN_Book_Statistics_for_Genomics_PCA#3]
Probably can have another pull request to add the authorship information. Happy to help with figuring out roles if needed, but feel free to check [Differential Expression](https://jhudatascience.org/GDSCN_Book_Statistics_for_Genomics_Differential_Expression/about-the-authors.html).

![image](https://user-images.githubusercontent.com/15618412/162449970-38dd146d-db2b-4459-aca8-38608153725b.png)

**Comment by ehumph** [comment]
I created a pull request with the updated About.Rmd. I'm not entirely certain I did it correctly. I created a new branch instead of updating pull request #1.
